In [139]:
import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.metrics import f1_score, confusion_matrix, precision_recall_curve, roc_curve
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Binarizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

dataset = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sub = pd.read_csv('submission.csv')

In [140]:
dataset.head(3)

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0

In [141]:
dataset[dataset['hour_bef_temperature'].isnull() == True]

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
934,1420,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0
1035,1553,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [142]:
def solve_nah(dataset):
    dataset['hour_bef_temperature'].fillna(dataset['hour_bef_temperature'].mean(), inplace=True)
    dataset['hour_bef_precipitation'].fillna(1, inplace=True)
    dataset['hour_bef_windspeed'].fillna(dataset['hour_bef_windspeed'].mean(), inplace=True)
    dataset['hour_bef_humidity'].fillna(dataset['hour_bef_humidity'].mean(), inplace=True)
    dataset['hour_bef_visibility'].fillna(dataset['hour_bef_visibility'].mean(), inplace=True)
    dataset['hour_bef_ozone'].fillna(dataset['hour_bef_ozone'].mean(), inplace=True)
    dataset['hour_bef_pm10'].fillna(dataset['hour_bef_pm10'].mean(), inplace=True)
    dataset['hour_bef_pm2.5'].fillna(dataset['hour_bef_pm2.5'].mean(), inplace=True)

In [143]:
solve_nah(dataset)
solve_nah(test)

In [144]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1459 non-null   int64
 1   hour                    1459 non-null   int64
 2   hour_bef_temperature    1459 non-null   float64
 3   hour_bef_precipitation  1459 non-null   float64
 4   hour_bef_windspeed      1459 non-null   float64
 5   hour_bef_humidity       1459 non-null   float64
 6   hour_bef_visibility     1459 non-null   float64
 7   hour_bef_ozone          1459 non-null   float64
 8   hour_bef_pm10           1459 non-null   float64
 9   hour_bef_pm2.5          1459 non-null   float64
 10  count                   1459 non-null   float64
dtypes: float64(9), int64(2)
memory usage: 125.5 KB

In [146]:
from sklearn.model_selection import train_test_split

X = dataset.drop('count', axis=1)
y = dataset['count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg = reg.fit(X_train, y_train)

pred = reg.predict(test)
pred

array([110.14533506, 240.0014845 ,  58.83625057, 115.03470769,
        93.967815  , 143.83600797, 160.471679  , 234.58118744,
        85.33840705,  26.44950699, 231.2824156 , 220.33808939,
       187.93513558,  99.23433858, 202.168418  , 211.60539259,
        73.65803899, 133.8590664 , 232.19689419, 187.9176439 ,
       234.05922027,  82.32728604, 101.39534373, 175.87256012,
       202.99732356, 166.75625546,  71.27577718, 147.17752993,
       134.81599423, 209.06317579,  68.80428487, 106.61441071,
       106.91771717, 197.81650019, 213.39524203, 103.63601738,
       186.19391105,  99.87059028, 254.36003061,  90.0693092 ,
        18.30311064, 175.25153332,  96.04505166,  91.75689909,
       239.02888701, 188.26336356,  47.33838228,  97.88635911,
        86.00670127,  84.62416031, 228.84376603, 106.20619827,
        87.83651567, 104.04532191, 212.90388366,  97.51981724,
        96.65274454, 188.52124278, 109.17893115,  81.96413123,
        98.01761559, 107.22277965, 194.92755512, 229.5162388 ,
       197.8944088 , 225.85378979,  83.51409808, 252.27549401,
       186.35288741, 105.63238693, 167.84222015,  62.92957246,
       110.01828949,  81.30481212, 237.71502043, 221.33270924,
        93.51465715, 199.69186049, 232.98285483,  87.86193566,
       219.97006413, 208.96174144,  96.34904633,  87.60685027,
        92.66631549, 216.64369735,  84.492795  , 202.26235276,
        84.10719241, 216.48383304, 215.6769886 , 183.33578987,
        93.9279827 , 161.55333334,  94.92559857,  72.38969039,
       124.34720275,  71.72842932, 202.41261932, 192.29794401,
        97.16762564, 201.18849879, -13.58833998, 126.14986274,
        82.18807172,  98.97172031, 150.60158056,  75.95557563,
       224.30823589, 119.45439275, 222.74406474, 228.75572144,
       200.58249177, 167.35834046,  82.47833252, 202.67683239,
       216.65890043,  83.38372063, 214.58626614,  97.06649066,
       166.85570214,  97.55285121, 131.73349966, 176.58848808,
       112.70063444, 133.44443279,  71.2993756 ,  71.73674391,
       203.53410979,  91.09307767, 193.65377905, 210.68372405,
        88.36646153, 212.48054156, 229.15064639, 201.14214911,
        93.79816851, 211.43349509, 205.71056909, 234.04640202,
        99.13288211,  77.95798085,  79.65167049,  71.90356459,
        96.66440934, 144.1000626 , 130.51216163, 138.30910212,
       204.27877654, 238.41424583, 210.15153825, 229.15820934,
       215.15092967, 234.13666815, 186.58945651,  10.80616528,
       121.1343622 ,  44.33539432,  98.0600301 , 214.51772459,
       224.42921348,  95.76136875, 196.41032322, 238.9464556 ,
       188.76692548,  92.10091578, 133.35959483, 170.37688753,
       223.12172467, 110.41304819, 121.69705688, 180.31867571,
        90.77873573, 181.74985427, 140.24452275, 119.34182616,
       201.92115795, 191.35684067, 228.22550408, 155.30162608,
       197.73541832, 108.8101034 , 217.54481439, 216.71164559,
       181.71965334,  91.42975116,  87.28849834, 229.52393066,
       196.27555661, 100.52369875,  78.47378114, 218.74780862,
       125.16441367, 175.09933169, 200.05119973, 233.23938381,
       224.09815387, 217.23777468, 188.57347956, 146.4525767 ,
        99.56096363, 133.93530464,  95.55784761, 227.25957843,
       192.19869347, 108.32419313, 175.09509527, 208.53797168,
       203.95056372,  86.61559488, 211.98898093, 123.33448848,
       190.93096108, 190.44517416, 213.49512513, 176.91811775,
       202.57817114, 130.39355064, 199.86992395, 113.28113416,
       104.35580138, 100.35858413, 157.94716414,  67.86969322,
       187.35088577,  83.69282104, 190.60127896, 179.63766345,
        92.61457733, 118.10029048, 228.19062181, 176.28257295,
       107.80015862,  97.12751105, 188.40116456, 153.81199181,
       232.33699915, 237.95783771, 175.82291542, 195.41790459,
        70.74832315, 214.69438423,  91.42873166, 169.44486763,
       193.17993268, 140.7199181 , 176.65430748, 196.71012843,
        87.29091761, 101.36550811,  92.53704176, 241.56986086,
       197.60032901, 110.86240384, 196.5098109 , 120.74846025,
        96.64958651, 231.12914078,  77.87343905,  90.24385466,
       224.12858735,  92.0739064 , 200.73147961,  87.64759209,
        98.19444009, 195.03418138, 112.21733842, 225.98548234,
        83.91428445, 209.74217277, 197.66544799, 131.65618414,
        79.6416538 , 224.96183044, 116.34468659, 223.25514107,
        88.27524188, 118.54565759, 114.44568396,  84.12149475,
       220.55855428, 144.96282533,  76.05185678, 212.91855109,
       107.12714068, 125.03830112, 209.70786046, 229.84356442,
       -11.22260976, 108.96277617, 181.14094531, 219.77364702,
       109.2563762 , 199.22906383, 182.17313032,  41.92207006,
       193.20388968, 111.30777307, 200.46229835,  -0.69510614,
       168.38359212, 200.54423128, 209.13629873, 248.88239562,
       246.70329089, 224.08947496, 174.9135017 ,  78.10173742,
       190.40189185,  93.72521248, 217.84489871, 214.14571556,
       217.53298835,  96.70630458, 219.76029165, 219.4993513 ,
       179.45088286,  89.06233831,  79.78913182,  91.539683  ,
       190.26507234,  69.97117312, 193.13244369, 160.4386012 ,
       106.15726722, 240.81611991, 212.12219281, 146.11944724,
        96.62807485,  40.26235485,  68.49705128, 113.60959016,
        91.40606971, 187.66811818, 168.49166023,  83.26128866,
       204.04940583, 216.03279583, 193.81967763, 227.47990969,
        82.38778952,  93.86145182, 235.52958711, 202.24322445,
       172.41325906,  98.87615014,  93.7484766 , 130.37808768,
       179.14159701, 219.36973699, 203.69061739, 232.59741162,
        23.92360591,  95.88172095, 225.11136246, 113.57767862,
        92.42027378, 117.04820257, 136.45453853, 173.44757869,
        90.23233337, 217.40138636, 207.84167592, 111.80307659,
       180.18533299, 112.3356906 ,  86.71182149, 175.95756576,
        96.64690069, 218.06158897, 145.93417872,  78.93064051,
       207.72025904, 219.40096079, 198.37112881,  78.43823556,
        92.46412894, 231.04274492, 107.78663057, 100.60609473,
        41.33899845, 156.32929671, 246.77767932, 221.5059212 ,
       186.49610101,  93.86006684, 189.2472672 , 197.96584959,
       123.1685241 , 226.75695403,  94.83013706, 180.37878795,
       221.85746909,  92.77003751, 109.90616929, 146.23074077,
       219.33860377,  84.51821045,  85.59437002, 193.46602044,
         4.62872743,  89.20818518,  80.07486609, 216.04516282,
       106.21439894, 127.19551622, 113.9780727 , 113.77743451,
       154.23250843, 116.35975667, 218.09357957, 226.78637307,
       190.77486024, 137.77060906, 105.14174662, 187.99746287,
       225.03209237, 154.95900372,  88.53242023,  65.7454798 ,
       118.78692747,  77.09282829,  97.09752832,  87.93551451,
       210.40210208, 117.56369616, 145.83062039, 228.55063221,
       134.28650138, 229.28926804, 181.94748867, 213.64369749,
       206.44751124, 158.47553807, 106.76414076, 176.10237532,
       235.94105447, 110.57914173, 147.37848119, 249.3161425 ,
       216.91330176, 195.63722452,  84.40683478, 138.73435207,
       166.73149528,  97.97382972, 151.70039214,  15.8602889 ,
       237.99063336, 218.23350997, 196.8779196 , 182.27843325,
       196.61395048, 195.21462999, 197.46337837, 168.61789908,
       207.0261692 ,  63.57749649,  98.52758149, 161.47290246,
       199.18246567, 176.12288542, 125.04176346, 160.31583834,
        82.06481533, 204.93508553, 214.82045494, 122.96696502,
       183.44900116, 211.05569464, 208.68280031,  85.67611015,
       214.00337888, 111.77055979, 122.08468323, 206.28846827,
       102.68994931,  18.26776316, 195.45699344, 214.23737359,
       139.61060365,  99.79269324,  75.03712247,  78.5174002 ,
       236.03366175, 178.99285672, 220.13642821, 209.9283324 ,
        84.15782261, 184.31166531, 217.05425023, 196.10257769,
        97.17163544,  22.32920925,  96.96954832, 125.37707286,
       170.30152714, 198.81801812, 220.35194436, 230.0515653 ,
        75.2512201 , 227.60426454,  81.00337378, 169.47075104,
       118.20851442, 228.85275544, 241.81001199,  79.06030093,
       190.55136457,  74.62095789, 113.20828092, 197.83425187,
       188.68674788, 205.65479109, 225.54250206,  51.48869421,
        79.84892398, 221.2494952 , 215.13252936, 120.23035436,
        99.73853234, 202.09639855,  83.49703976,  75.44311898,
       107.1668025 ,  61.712618  , 103.20422577, 204.83757642,
       208.233925  , 191.26832849,  84.1328109 , 105.89633386,
        81.46550925, 228.10489074, 143.56007164, 106.05973282,
       156.70035332,  83.77406142,  65.35196335,  68.83027401,
       225.97431933,  78.20859399, 211.6049535 , 203.16738313,
       225.40178865, 212.63273797, 170.03526392, 102.73333063,
       158.06434199, 125.54564891, 194.17560373,  96.50953938,
        69.96937944, 162.54578827,  83.87668582, 111.29488603,
       159.798462  , 119.17221395, 182.93179308, 229.65897274,
       225.05146193, 232.3241146 ,  75.30150892, 153.90803482,
        78.77827121, 102.4779605 , 134.63355249, 108.34121744,
        79.37495962, 201.95837127,  98.66817656, 209.51276006,
       179.68986928, 236.30906133, 202.59582526, 217.37971059,
       178.54623978, 221.31099024,  72.41083754, 105.15053921,
        76.79147759,  66.27806402,  71.69244471,  99.81324507,
       105.09054723, 141.35773193, 105.04380934, 216.03898194,
       191.78733828, 196.96387064,  69.01811538,  78.46542451,
        95.36249006, 181.97854415, 121.54443136, 182.16162343,
       231.94731313,  93.71714041, 199.50145712, 157.53399887,
        70.80288593, 234.75497417, 152.4792407 ,  87.85140969,
        95.76900053, 213.13056844,  26.07314303, 233.46614913,
       225.52706032, 197.73886527, 225.82501676, 199.13787308,
       101.40664774, 142.77962411, 142.43095067, 117.72250114,
        71.12527052,  78.30208537, 238.06583452, 132.38304277,
        83.09536153, 181.66067391, 128.13739913, 209.39310943,
       101.34313841, 222.25013818, 108.8677617 ,  19.66661601,
        76.15347731, 245.62220095, 212.66461573,  60.5162424 ,
       116.26277961,  76.82691733, 143.37988035, 163.74710634,
       229.59339649, 180.30614691, 106.78966651,  97.90891965,
       108.08652721, 152.62213954, 105.29241758, 131.62922703,
       247.19657507, 177.48929267, 208.36415241, 165.05815615,
       223.99260324, 201.05407377, 101.1607751 , 117.41868247,
       134.57757908, 128.61696492, 251.10929398, 207.96680746,
       150.73813817, 143.73305171, 195.02835519,  88.91138299,
       183.02231539, 204.97121141,  96.38062348,  70.43383983,
       146.03302336, 141.82289959,  92.94344774, 179.01248033,
       198.25817533,  77.40186817, 147.21195563, 175.29204114,
       224.00567055, 129.86259287,  87.32579738, 199.260881  ,
        77.71280246, 101.7500165 ,  73.69125779,  70.21434061,
       104.24015274, 205.37176998, 151.1969423 , 197.00816712,
       210.43512789, 199.53254375, 160.65533194,  90.21674532,
       106.17036842,  85.12057635, 179.17554046,  87.66188337,
        98.40024084, 121.21816394,  84.23434814, 229.15772744,
        67.76857618,  23.87672275, 223.71474074,  86.42661468,
       225.31628848, 241.43042152,  72.36757486, 237.41911811,
       153.45742818, 219.81629554,  83.5629965 ,  71.52574782,
       114.19306963, 203.63071184, 110.02132375,  70.04867307,
       137.99855667, 190.65449444, 113.54789916])

In [136]:
sub['count'] = pred

In [138]:
sub.to_csv('submission.csv',encoding='utf-8-sig', index=False)